Repository AY2425S1-CS2113-W13-1/tp, pull requests merged in 2024-11, with the labels that each got.

#121 Create draft PPP
  docs/team/3ccly.md
  src/test/java/ymfc/ui/UiTest.java
Labels: priority.High

#125 Add PPP for gskang
  docs/team/gskang.md
Labels: type.Task

#131 Close Issue #72 and #76
  src/main/java/ymfc/commands/DeleteIngredientCommand.java
  src/main/java/ymfc/list/IngredientList.java
  src/main/java/ymfc/list/RecipeList.java
  src/main/java/ymfc/parser/Parser.java
  src/test/java/ymfc/list/IngredientListTest.java
  src/test/java/ymfc/list/RecipeListTest.java
Labels: type.Enhancement, type.Task, type.Bug

#128 Correct issues in DG pointed out by TA
  docs/DeveloperGuide.md
  docs/img/ClassDiagrams/ArchitectureDiagram.png
  docs/img/ClassDiagrams/commandsShortClassDiagram.png
  docs/img/SequenceDiagrams/AddRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/ApplicationStartUp.png
  docs/img/SequenceDiagrams/EditRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/Parser.parseCommand.png
  docs/img/SequenceDiagrams/loadRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/parseCommandShortSequenceDiagram.png
  docs/img/SequenceDiagrams/saveRecipesSequenceDiagram.png
  docs/puml/ClassDiagrams/ArchitectureDiagram.puml
  docs/puml/ClassDiagrams/CommandClassesShort.puml
  docs/puml/SequenceDiagrams/AddRecipes.puml
  docs/puml/SequenceDiagrams/ApplicationStartUp.puml
  docs/puml/SequenceDiagrams/EditRecipes.puml
  docs/puml/SequenceDiagrams/LoadRecipes.puml
  docs/puml/SequenceDiagrams/Parser.parseCommand.puml
  docs/puml/SequenceDiagrams/SaveRecipes.puml
  docs/puml/SequenceDiagrams/Style.puml
  docs/puml/SequenceDiagrams/parseCommandShort.puml
  docs/team/ksanjith.md
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/storage/Storage.java
Labels: priority.High

#135 Update Recipe class ingredients list type to ArrayList of Ingredients
  src/main/java/ymfc/commands/FindCommand.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/recipe/Recipe.java
  src/test/java/ymfc/commands/AddRecipeCommandTest.java
  src/test/java/ymfc/commands/DeleteCommandTest.java
  src/test/java/ymfc/commands/EditCommandTest.java
  src/test/java/ymfc/commands/FindCommandTest.java
  src/test/java/ymfc/commands/FindIngredCommandTest.java
  src/test/java/ymfc/commands/SortCommandTest.java
  src/test/java/ymfc/list/RecipeListTest.java
  src/test/java/ymfc/parser/ParserTest.java
  src/test/java/ymfc/recipe/RecipeTest.java
Labels: type.Task

#134 Implement recommend function to application
  src/main/java/ymfc/commands/EditCommand.java
  src/main/java/ymfc/commands/RandomCommand.java
  src/main/java/ymfc/commands/RecommendCommand.java
  src/main/java/ymfc/ingredient/Ingredient.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/recipe/RecommendedRecipe.java
  src/main/java/ymfc/recipe/SortByPercentMatch.java
  src/main/java/ymfc/ui/Ui.java
  src/test/java/ymfc/commands/EditCommandTest.java
Labels: type.Task, priority.High

#136 Addition to DG
  docs/DeveloperGuide.md
  src/main/java/ymfc/recipe/RecommendedRecipe.java
Labels: type.Task

#153 Standardise and update documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/ClassDiagrams/commandsClassDiagram.png
  docs/img/ClassDiagrams/commandsShortClassDiagram.png
  docs/img/ClassDiagrams/ingredientsClassDiagram.png
  docs/img/ClassDiagrams/recipesClassDiagram.png
  docs/img/SequenceDiagrams/AddRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/LoadRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/ParseCommandShortSequenceDiagram.png
  docs/img/SequenceDiagrams/Parser.parseCommand.png
  docs/img/SequenceDiagrams/SaveRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/loadRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/parseCommandShortSequenceDiagram.png
  docs/puml/ClassDiagrams/CommandClasses.puml
  docs/puml/ClassDiagrams/CommandClassesShort.puml
  docs/puml/ClassDiagrams/RecipeClassDiagram.puml
  docs/puml/ClassDiagrams/ingredientsClassDiagram.puml
  docs/puml/SequenceDiagrams/AddRecipes.puml
  docs/puml/SequenceDiagrams/LoadRecipes.puml
  docs/puml/SequenceDiagrams/Parser.parseCommand.puml
  docs/puml/SequenceDiagrams/parseCommandShort.puml
  src/main/java/ymfc/commands/SortIngredientCommand.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/ui/Ui.java
  src/test/java/ymfc/commands/SortIngredientCommandTest.java
  src/test/java/ymfc/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#154 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#216 Improve edit command functionality
  docs/UserGuide.md
  src/main/java/ymfc/commands/EditCommand.java
  src/main/java/ymfc/list/RecipeList.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/ui/Ui.java
  src/test/java/ymfc/commands/EditCommandTest.java
  src/test/java/ymfc/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, type.Bug, priority.High, severity.Medium, Documentation, Improvements, Critical

#219 Updates storage related documentations
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/SequenceDiagrams/LoadRecipesSequenceDiagram.png
  docs/img/SequenceDiagrams/SaveRecipesSequenceDiagram.png
  docs/puml/SequenceDiagrams/SaveRecipes.puml
  docs/puml/SequenceDiagrams/UpdatedLoadRecipes.puml
  src/main/java/ymfc/ingredient/Ingredient.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/recipe/Recipe.java
  src/main/java/ymfc/storage/Storage.java
  src/main/java/ymfc/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, Documentation, Improvements

#222 Debug: fix parser validateStepNumbers()
  src/main/java/ymfc/parser/Parser.java
Labels: type.Bug, Critical

#227 Make recommend command ignore case for ingredients
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/SequenceDiagrams/EditRecipesSequenceDiagram.png
  docs/puml/SequenceDiagrams/EditRecipes.puml
  docs/team/3ccly.md
  src/main/java/ymfc/commands/RecommendCommand.java
  src/main/java/ymfc/parser/Parser.java
  src/test/java/ymfc/commands/RecommendCommandTest.java
Labels: type.Task, type.Bug, Improvements

#240 Finalise PPP
  docs/team/3ccly.md
Labels: Documentation
