Repository AY2425S1-CS2113-W13-1/tp, pull requests merged in 2024-10, with the labels that each got.

#67 Add sort command
  src/main/java/ymfc/commands/SortCommand.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/recipelist/RecipeList.java
  src/test/java/ymfc/commands/SortCommandTest.java
Labels: type.Task

#88 Create first draft of the UG
  docs/UserGuide.md
  src/main/java/ymfc/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#93 Bug fixes for commands
  src/main/java/ymfc/commands/AddIngredientCommand.java
  src/main/java/ymfc/parser/Parser.java
  src/main/java/ymfc/recipe/Recipe.java
  src/main/java/ymfc/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, priority.High

#95 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.Low

#98 Prevent user from creating duplicate recipes
  UMLDiagrams/ClassDiagrams/CommandClasses.puml
  UMLDiagrams/ClassDiagrams/Style.puml
  UMLDiagrams/SequenceDiagrams/ApplicationStartUp.puml
  UMLDiagrams/SequenceDiagrams/LoadRecipes.puml
  UMLDiagrams/SequenceDiagrams/SaveRecipes.puml
  UMLDiagrams/SequenceDiagrams/Style.puml
  docs/DeveloperGuide.md
  docs/commandsClassDiagram.png
  docs/loadRecipesSequenceDiagram.png
  src/main/java/ymfc/commands/AddRecipeCommand.java
  src/main/java/ymfc/ingredient/Ingredient.java
  src/main/java/ymfc/recipe/Recipe.java
  src/main/java/ymfc/storage/Storage.java
  src/main/java/ymfc/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#103 Fix formatting issues, update developer guide
  docs/DeveloperGuide.md
  src/main/java/ymfc/commands/EditCommand.java
  src/main/java/ymfc/list/RecipeList.java
  src/main/java/ymfc/recipe/Recipe.java
  src/main/java/ymfc/ui/Ui.java
  src/test/java/ymfc/recipe/RecipeTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, type.Bug, priority.Medium

#104 Add architecture diagram to Developer Guide
  docs/ApplicationStartUpSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/img/ClassDiagrams/ArchitectureDiagram.png
  docs/puml/ClassDiagrams/ArchitectureDiagram.puml
  docs/puml/SequenceDiagrams/ApplicationStartUp.puml
Labels: type.Task, priority.High

#108 Add ingredients class diagram
  docs/DeveloperGuide.md
  docs/img/ClassDiagrams/commandsClassDiagram.png
  docs/img/ClassDiagrams/ingredientsClassDiagram.png
  docs/puml/ClassDiagrams/CommandClasses.puml
  docs/puml/ClassDiagrams/ingredientsClassDiagram.puml
  src/main/java/ymfc/ingredient/Ingredient.java
  src/main/java/ymfc/list/IngredientList.java
Labels: type.Enhancement, priority.High

#110 docs: Update `Recipe` and `RecipeList` sections of DG
  docs/DeveloperGuide.md
  docs/img/ClassDiagrams/RecipeClassDiagram.png
  docs/puml/ClassDiagrams/RecipeClassDiagram.puml
  src/main/java/ymfc/recipe/Recipe.java
Labels: type.Enhancement, priority.High
